/// Renders emission models as Swift source text.
///
/// Emission is plain string templating (spec §6 allows templating or
/// SwiftSyntax); templating keeps the output — and the templates themselves —
/// readable and reviewable as normal diffs.
enum Emitter {
    /// The banner prepended to every generated file.
    private static let header = """
        // Generated by acp-generate from the vendored ACP JSON schema.
        // DO NOT EDIT. Regenerate with: swift run acp-generate
        """

    /// The indentation prefix for one nesting level.
    private static let indentUnit = "    "

    /// Assembles a generated file from rendered declarations.
    ///
    /// - Parameters:
    ///   - declarations: Rendered type declarations, already sorted.
    ///   - namespace: An enclosing namespace enum to nest the declarations in,
    ///     or `nil` to emit them at the top level.
    /// - Returns: The complete file text, header included.
    static func file(declarations: [String], namespace: String? = nil) -> String {
        guard let namespace else {
            return ([header] + declarations).joined(separator: "\n\n") + "\n"
        }
        let nested = declarations.map(indented(declaration:)).joined(separator: "\n\n")
        let wrapped = "public enum \(namespace) {\n\(nested)\n}"
        return ([header, wrapped]).joined(separator: "\n\n") + "\n"
    }

    /// Indents every non-empty line of a declaration by one nesting level.
    ///
    /// - Parameter declaration: The rendered declaration text.
    /// - Returns: The declaration with each non-empty line prefixed.
    private static func indented(declaration: String) -> String {
        declaration
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "\(indentUnit)\($0)" }
            .joined(separator: "\n")
    }

    /// Renders schema-derived text as an escaped Swift string literal.
    ///
    /// Backslashes and quotes are escaped so no schema value can break out
    /// of the generated source. `swiftCaseName` already rejects such values
    /// at the generator boundary; the emitter stays safe on its own terms.
    ///
    /// - Parameter text: The schema-derived text (wire name, value, or tag).
    /// - Returns: The quoted, escaped Swift string literal.
    static func stringLiteral(_ text: String) -> String {
        let escaped = text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    /// Renders a distinct ID newtype wrapping a wire string.
    ///
    /// - Parameters:
    ///   - name: The emitted Swift type name.
    ///   - documentation: The schema description, if any.
    /// - Returns: The rendered struct declaration.
    static func identifierNewtype(name: String, documentation: String?) -> String {
        var lines = docLines(documentation, indent: "")
        lines.append(contentsOf: [
            "public struct \(name): WireRawValueCodable, Hashable, Sendable {",
            "    /// The opaque identifier string as it crosses the wire.",
            "    public let rawValue: String",
            "",
            "    /// Creates a `\(name)` wrapping the given wire string.",
            "    ///",
            "    /// - Parameter rawValue: The opaque identifier string.",
            "    public init(rawValue: String) {",
            "        self.rawValue = rawValue",
            "    }",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    /// Renders a placeholder typealias seam.
    ///
    /// Covers definitions deferred to a later generator stage as well as
    /// permanently free-form definitions.
    ///
    /// - Parameters:
    ///   - name: The emitted Swift type name.
    ///   - reason: Why the definition is unresolved (e.g. `oneOf union`).
    ///   - documentation: The schema description, if any.
    /// - Returns: The rendered typealias declaration.
    static func placeholder(name: String, reason: String, documentation: String?) -> String {
        var lines = docLines(documentation, indent: "")
        if !lines.isEmpty {
            lines.append("///")
        }
        lines.append("/// \(reason)")
        lines.append("public typealias \(name) = JSONValue")
        return lines.joined(separator: "\n")
    }

    /// Renders an object struct declaration.
    ///
    /// The struct carries explicit CodingKeys, a public memberwise
    /// initializer, forgiving decoding, and nil-omitting encoding.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The rendered struct declaration.
    static func structDeclaration(_ model: StructModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public struct \(model.name): Codable, Hashable, Sendable {")
        guard !model.properties.isEmpty else {
            lines.append(contentsOf: [
                "    /// Creates a `\(model.name)`.",
                "    public init() {}",
                "}",
            ])
            return lines.joined(separator: "\n")
        }

        for (index, property) in model.properties.enumerated() {
            if index > 0 { lines.append("") }
            lines.append(contentsOf: docLines(property.documentation, indent: "    "))
            lines.append("    public var \(property.swiftName): \(renderedType(of: property))")
        }

        lines.append("")
        lines.append(contentsOf: memberwiseInit(model))
        lines.append("")
        lines.append(contentsOf: codingKeys(model))
        lines.append("")
        lines.append(contentsOf: decoderInit(model))
        lines.append("")
        lines.append(contentsOf: encodeMethod(model))
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Struct members

    /// Renders the property's full Swift type, `?` included.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The type expression as written after the colon.
    private static func renderedType(of property: PropertyModel) -> String {
        property.typeExpression + (property.isOptional ? "?" : "")
    }

    /// Renders the public memberwise initializer.
    ///
    /// Optional parameters default to `nil`; defaulted parameters use their
    /// schema default.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The initializer lines, indented one level.
    private static func memberwiseInit(_ model: StructModel) -> [String] {
        var lines = ["    /// Creates a `\(model.name)`.", "    public init("]
        for (index, property) in model.properties.enumerated() {
            var parameter = "        \(property.swiftName): \(renderedType(of: property))"
            if let defaultExpression = property.defaultExpression {
                parameter += " = \(defaultExpression)"
            } else if property.isOptional {
                parameter += " = nil"
            }
            if index < model.properties.count - 1 {
                parameter += ","
            }
            lines.append(parameter)
        }
        lines.append("    ) {")
        for property in model.properties {
            lines.append("        self.\(property.swiftName) = \(property.swiftName)")
        }
        lines.append("    }")
        return lines
    }

    /// Renders the explicit CodingKeys enum mapping Swift names to wire names.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The enum lines, indented one level.
    private static func codingKeys(_ model: StructModel) -> [String] {
        var lines = ["    private enum CodingKeys: String, CodingKey {"]
        for property in model.properties {
            if property.swiftName == property.wireName {
                lines.append("        case \(property.swiftName)")
            } else {
                lines.append("        case \(property.swiftName) = \(stringLiteral(property.wireName))")
            }
        }
        lines.append("    }")
        return lines
    }

    /// Renders `init(from:)`.
    ///
    /// Invariant fields decode strictly; annotated fields decode through
    /// the forgiving helpers.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The initializer lines, indented one level.
    private static func decoderInit(_ model: StructModel) -> [String] {
        var lines = [
            "    /// Decodes a `\(model.name)`; forgiving fields degrade to their",
            "    /// schema defaults instead of failing the message.",
            "    ///",
            "    /// - Parameter decoder: The decoder positioned at the object.",
            "    /// - Throws: `DecodingError` when a strict field is missing, mistyped,",
            "    ///   or violates a wire invariant.",
            "    public init(from decoder: any Decoder) throws {",
            "        let container = try decoder.container(keyedBy: CodingKeys.self)",
        ]
        for property in model.properties {
            lines.append("        " + decodeLine(property))
        }
        lines.append("    }")
        return lines
    }

    /// Renders the single decode statement for a property.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `self.x = …` statement.
    private static func decodeLine(_ property: PropertyModel) -> String {
        let name = property.swiftName
        let type = property.typeExpression
        switch property.strategy {
        case .strict:
            if let defaultExpression = property.defaultExpression {
                return "self.\(name) = try container.decodeIfPresent(\(type).self, forKey: .\(name)) ?? \(defaultExpression)"
            }
            if property.isOptional {
                return "self.\(name) = try container.decodeIfPresent(\(type).self, forKey: .\(name))"
            }
            return "self.\(name) = try container.decode(\(type).self, forKey: .\(name))"
        case .forgivingScalar:
            if let defaultExpression = property.defaultExpression {
                return "self.\(name) = container.forgivingDecode(\(type).self, forKey: .\(name), default: \(defaultExpression))"
            }
            return "self.\(name) = container.forgivingDecodeIfPresent(\(type).self, forKey: .\(name))"
        case .forgivingArray:
            let element = property.elementType ?? type
            if property.isOptional {
                return "self.\(name) = container.forgivingDecodeArrayIfPresent(of: \(element).self, forKey: .\(name))"
            }
            return "self.\(name) = container.forgivingDecodeArray(of: \(element).self, forKey: .\(name))"
        }
    }

    /// Renders `encode(to:)`, omitting `nil` optional fields entirely.
    ///
    /// This mirrors `init(from:)`, which decodes every optional property via
    /// `decodeIfPresent`, so both directions apply the same condition.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The method lines, indented one level.
    private static func encodeMethod(_ model: StructModel) -> [String] {
        var lines = [
            "    /// Encodes a `\(model.name)`, omitting nil optional fields — never",
            "    /// emitting JSON null for an absent capability-gated field.",
            "    ///",
            "    /// - Parameter encoder: The encoder to write the object into.",
            "    /// - Throws: Rethrows any error from the underlying encoder.",
            "    public func encode(to encoder: any Encoder) throws {",
            "        var container = encoder.container(keyedBy: CodingKeys.self)",
        ]
        for property in model.properties {
            let name = property.swiftName
            if property.isOptional {
                lines.append("        try container.encodeIfPresent(\(name), forKey: .\(name))")
            } else {
                lines.append("        try container.encode(\(name), forKey: .\(name))")
            }
        }
        lines.append("    }")
        return lines
    }

    // MARK: - Unions

    /// Renders a string enum with hand-rolled `Codable`.
    ///
    /// Known snake_case wire strings map to camelCase cases, anything else
    /// decodes to `unknown(String)`, and `.unknown` re-encodes its captured
    /// string.
    ///
    /// - Parameter model: The enum's emission model.
    /// - Returns: The rendered enum declaration.
    static func stringEnumDeclaration(_ model: StringEnumModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public enum \(model.name): Codable, Hashable, Sendable {")
        for enumCase in model.cases {
            lines.append(contentsOf: docLines(enumCase.documentation, indent: "    "))
            lines.append("    case \(enumCase.swiftName)")
            lines.append("")
        }
        lines.append(contentsOf: [
            "    /// An unrecognized wire value, captured verbatim so a newer peer's",
            "    /// value decodes without error and re-encodes unchanged.",
            "    case unknown(String)",
            "",
            "    /// The string as it crosses the wire.",
            "    public var wireValue: String {",
            "        switch self {",
        ])
        for enumCase in model.cases {
            lines.append("        case .\(enumCase.swiftName): \(stringLiteral(enumCase.wireValue))")
        }
        lines.append(contentsOf: [
            "        case .unknown(let value): value",
            "        }",
            "    }",
            "",
            "    /// Creates the case matching a wire string, routing unrecognized",
            "    /// values to `.unknown`.",
            "    ///",
            "    /// - Parameter wireValue: The string as it crosses the wire.",
            "    public init(wireValue: String) {",
            "        switch wireValue {",
        ])
        for enumCase in model.cases {
            lines.append("        case \(stringLiteral(enumCase.wireValue)): self = .\(enumCase.swiftName)")
        }
        lines.append(contentsOf: [
            "        default: self = .unknown(wireValue)",
            "        }",
            "    }",
            "",
            "    /// Decodes the wire string, never failing on unrecognized values.",
            "    ///",
            "    /// - Parameter decoder: The decoder positioned at the string.",
            "    /// - Throws: `DecodingError` when the wire value is not a string.",
            "    public init(from decoder: any Decoder) throws {",
            "        self.init(wireValue: try decoder.singleValueContainer().decode(String.self))",
            "    }",
            "",
            "    /// Encodes the wire string; `.unknown` re-emits its captured string.",
            "    ///",
            "    /// - Parameter encoder: The encoder to write the string into.",
            "    /// - Throws: Rethrows any error from the underlying encoder.",
            "    public func encode(to encoder: any Encoder) throws {",
            "        var container = encoder.singleValueContainer()",
            "        try container.encode(wireValue)",
            "    }",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    /// Renders a tagged union as an enum with hand-rolled `Codable`.
    ///
    /// Cases carry associated payload values and coding is keyed on the
    /// discriminator: the payload's fields sit flattened beside the
    /// discriminator (serde's internally-tagged representation), and
    /// unrecognized discriminators decode to `unknown(String)`.
    ///
    /// - Parameter model: The union's emission model.
    /// - Returns: The rendered enum declaration.
    static func taggedUnionDeclaration(_ model: TaggedUnionModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public enum \(model.name): Codable, Hashable, Sendable {")
        for unionCase in model.cases {
            lines.append(contentsOf: docLines(unionCase.documentation, indent: "    "))
            if let payload = unionCase.payloadType {
                lines.append("    case \(unionCase.swiftName)(\(payload))")
            } else {
                lines.append("    case \(unionCase.swiftName)")
            }
            lines.append("")
        }
        lines.append(contentsOf: [
            "    /// An unrecognized discriminator value, captured so decoding never",
            "    /// fails. Re-encoding emits only the discriminator; an unrecognized",
            "    /// variant's payload fields are not preserved.",
            "    case unknown(String)",
            "",
            "    private enum CodingKeys: String, CodingKey {",
            "        case \(model.discriminator)",
            "    }",
            "",
            "    /// Decodes by the `\(model.discriminator)` discriminator, routing",
            "    /// unrecognized values to `.unknown`.",
            "    ///",
            "    /// - Parameter decoder: The decoder positioned at the object.",
            "    /// - Throws: `DecodingError` when the discriminator is missing or a",
            "    ///   known variant's payload is malformed.",
            "    public init(from decoder: any Decoder) throws {",
            "        let container = try decoder.container(keyedBy: CodingKeys.self)",
            "        switch try container.decode(String.self, forKey: .\(model.discriminator)) {",
        ])
        for unionCase in model.cases {
            lines.append("        case \(stringLiteral(unionCase.tag)):")
            if let payload = unionCase.payloadType {
                lines.append("            self = .\(unionCase.swiftName)(try \(payload)(from: decoder))")
            } else {
                lines.append("            self = .\(unionCase.swiftName)")
            }
        }
        lines.append(contentsOf: [
            "        case let other:",
            "            self = .unknown(other)",
            "        }",
            "    }",
            "",
            "    /// Encodes the `\(model.discriminator)` discriminator, flattening the",
            "    /// payload's fields into the same object.",
            "    ///",
            "    /// - Parameter encoder: The encoder to write the object into.",
            "    /// - Throws: Rethrows any error from the underlying encoder.",
            "    public func encode(to encoder: any Encoder) throws {",
            "        var container = encoder.container(keyedBy: CodingKeys.self)",
            "        switch self {",
        ])
        for unionCase in model.cases {
            if unionCase.payloadType != nil {
                lines.append("        case .\(unionCase.swiftName)(let payload):")
                lines.append("            try container.encode(\(stringLiteral(unionCase.tag)), forKey: .\(model.discriminator))")
                lines.append("            try payload.encode(to: encoder)")
            } else {
                lines.append("        case .\(unionCase.swiftName):")
                lines.append("            try container.encode(\(stringLiteral(unionCase.tag)), forKey: .\(model.discriminator))")
            }
        }
        lines.append(contentsOf: [
            "        case .unknown(let discriminator):",
            "            try container.encode(discriminator, forKey: .\(model.discriminator))",
            "        }",
            "    }",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    // MARK: - Documentation

    /// Renders a schema description as doc-comment lines.
    ///
    /// - Parameters:
    ///   - text: The schema `description`, if any.
    ///   - indent: The indentation prefix for each line.
    /// - Returns: `///` lines, or empty when there is no description.
    private static func docLines(_ text: String?, indent: String) -> [String] {
        guard let text, !text.isEmpty else { return [] }
        return text.split(separator: "\n", omittingEmptySubsequences: false).map { line in
            line.isEmpty ? "\(indent)///" : "\(indent)/// \(line)"
        }
    }
}
