/// Renders emission models as Swift source text.
///
/// Emission is plain string templating (spec §6 allows templating or
/// SwiftSyntax); templating keeps the output — and the templates themselves —
/// readable and reviewable as normal diffs.
enum Emitter {
    /// The banner prepended to every generated file.
    private static let header = """
        // Generated by acp-generate from the vendored ACP JSON schema.
        // DO NOT EDIT. Regenerate with: swift run acp-generate
        """

    /// The indentation prefix for one nesting level.
    private static let indentUnit = "    "

    /// The indentation prefix for two nesting levels.
    private static let indent2 = indentUnit + indentUnit

    /// The indentation prefix for three nesting levels.
    private static let indent3 = indentUnit + indent2

    /// The indentation prefix for four nesting levels.
    private static let indent4 = indent2 + indent2

    /// Assembles a generated file from rendered declarations.
    ///
    /// - Parameters:
    ///   - declarations: Rendered type declarations, already sorted.
    ///   - namespace: An enclosing namespace enum to nest the declarations in,
    ///     or `nil` to emit them at the top level.
    /// - Returns: The complete file text, header included.
    static func file(declarations: [String], namespace: String? = nil) -> String {
        guard let namespace else {
            return ([header] + declarations).joined(separator: "\n\n") + "\n"
        }
        let nested = declarations.map(indented(declaration:)).joined(separator: "\n\n")
        let wrapped = "public enum \(namespace) {\n\(nested)\n}"
        return ([header, wrapped]).joined(separator: "\n\n") + "\n"
    }

    /// Indents every non-empty line of a declaration by one nesting level.
    ///
    /// - Parameter declaration: The rendered declaration text.
    /// - Returns: The declaration with each non-empty line prefixed.
    private static func indented(declaration: String) -> String {
        declaration
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "\(indentUnit)\($0)" }
            .joined(separator: "\n")
    }

    /// Renders schema-derived text as an escaped Swift string literal.
    ///
    /// Backslashes and quotes are escaped so no schema value can break out
    /// of the generated source. `swiftCaseName` already rejects such values
    /// at the generator boundary; the emitter stays safe on its own terms.
    ///
    /// - Parameter text: The schema-derived text (wire name, value, or tag).
    /// - Returns: The quoted, escaped Swift string literal.
    static func stringLiteral(_ text: String) -> String {
        let escaped = text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    /// Renders a distinct ID newtype wrapping a wire string.
    ///
    /// - Parameters:
    ///   - name: The emitted Swift type name.
    ///   - documentation: The schema description, if any.
    /// - Returns: The rendered struct declaration.
    static func identifierNewtype(name: String, documentation: String?) -> String {
        var lines = docLines(documentation, indent: "")
        lines.append(contentsOf: [
            "public struct \(name): WireRawValueCodable, Hashable, Sendable {",
            indentUnit + "/// The opaque identifier string as it crosses the wire.",
            indentUnit + "public let rawValue: String",
            "",
            indentUnit + "/// Creates a `\(name)` wrapping the given wire string.",
            indentUnit + "///",
            indentUnit + "/// - Parameter rawValue: The opaque identifier string.",
            indentUnit + "public init(rawValue: String) {",
            indent2 + "self.rawValue = rawValue",
            indentUnit + "}",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    /// Renders a placeholder typealias seam.
    ///
    /// Covers definitions deferred to a later generator stage as well as
    /// permanently free-form definitions.
    ///
    /// - Parameters:
    ///   - name: The emitted Swift type name.
    ///   - reason: Why the definition is unresolved (e.g. `oneOf union`).
    ///   - documentation: The schema description, if any.
    /// - Returns: The rendered typealias declaration.
    static func placeholder(name: String, reason: String, documentation: String?) -> String {
        var lines = docLines(documentation, indent: "")
        if !lines.isEmpty {
            lines.append("///")
        }
        lines.append("/// \(reason)")
        lines.append("public typealias \(name) = JSONValue")
        return lines.joined(separator: "\n")
    }

    /// Renders an object struct declaration.
    ///
    /// The struct carries explicit CodingKeys, a public memberwise
    /// initializer, forgiving decoding, and nil-omitting encoding.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The rendered struct declaration.
    static func structDeclaration(_ model: StructModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public struct \(model.name): Codable, Hashable, Sendable {")
        guard !model.properties.isEmpty else {
            lines.append(contentsOf: [
                indentUnit + "/// Creates a `\(model.name)`.",
                indentUnit + "public init() {}",
                "}",
            ])
            return lines.joined(separator: "\n")
        }

        for (index, property) in model.properties.enumerated() {
            if index > 0 { lines.append("") }
            lines.append(contentsOf: docLines(property.documentation, indent: indentUnit))
            lines.append(indentUnit + "public var \(property.swiftName): \(renderedType(of: property))")
        }

        lines.append("")
        lines.append(contentsOf: memberwiseInit(model))
        lines.append("")
        lines.append(contentsOf: codingKeys(model))
        lines.append("")
        lines.append(contentsOf: decoderInit(model))
        lines.append("")
        lines.append(contentsOf: encodeMethod(model))
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Struct members

    /// Renders the property's full Swift type: `PatchField<Wrapped>` for a
    /// field with patch semantics, otherwise the plain type with `?` when
    /// optional.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The type expression as written after the colon.
    private static func renderedType(of property: PropertyModel) -> String {
        if property.hasPatchSemantics {
            return "PatchField<\(property.typeExpression)>"
        }
        return property.typeExpression + (property.isOptional ? "?" : "")
    }

    /// Renders the public memberwise initializer.
    ///
    /// Optional parameters default to `nil`; defaulted parameters use their
    /// schema default.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The initializer lines, indented one level.
    private static func memberwiseInit(_ model: StructModel) -> [String] {
        var lines = [indentUnit + "/// Creates a `\(model.name)`.", indentUnit + "public init("]
        lines.append(contentsOf: renderParameters(items: model.properties, render: initParameter))
        lines.append(indentUnit + ") {")
        for property in model.properties {
            lines.append(indent2 + "self.\(property.swiftName) = \(property.swiftName)")
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders one initializer parameter with its default, if any.
    ///
    /// A patch-semantics field defaults to `.unchanged` — the state an
    /// omitted wire field decodes to. Otherwise, optional parameters default
    /// to `nil`; defaulted parameters use their schema default.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `name: Type[ = default]` fragment, without indentation.
    private static func initParameter(_ property: PropertyModel) -> String {
        var parameter = "\(property.swiftName): \(renderedType(of: property))"
        if property.hasPatchSemantics {
            parameter += " = .unchanged"
        } else if let defaultExpression = property.defaultExpression {
            parameter += " = \(defaultExpression)"
        } else if property.isOptional {
            parameter += " = nil"
        }
        return parameter
    }

    /// Renders a parenthesized parameter list's body: one item per line, indented one level, comma-terminated except the last.
    ///
    /// Shared by every initializer emitter so the comma bookkeeping lives in
    /// one place rather than being repeated at each call site.
    ///
    /// - Parameters:
    ///   - items: The parameters to render, in order.
    ///   - render: Renders one item to its `name: Type[ = default]` fragment.
    /// - Returns: The parameter lines, without the surrounding `(` and `)`.
    private static func renderParameters<T>(items: [T], render: (T) -> String) -> [String] {
        items.enumerated().map { index, item in
            let comma = index < items.count - 1 ? "," : ""
            return indent2 + render(item) + comma
        }
    }

    /// Renders the explicit CodingKeys enum mapping Swift names to wire names.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The enum lines, indented one level.
    private static func codingKeys(_ model: StructModel) -> [String] {
        var lines = [indentUnit + "private enum CodingKeys: String, CodingKey {"]
        for property in model.properties {
            lines.append(indent2 + codingKeyCase(property))
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders one `CodingKeys` case, mapping the Swift name to its wire name.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `case …` line, without indentation.
    private static func codingKeyCase(_ property: PropertyModel) -> String {
        if property.swiftName == property.wireName {
            return "case \(property.swiftName)"
        }
        return "case \(property.swiftName) = \(stringLiteral(property.wireName))"
    }

    /// Renders `init(from:)`.
    ///
    /// Invariant fields decode strictly; annotated fields decode through
    /// the forgiving helpers.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The initializer lines, indented one level.
    private static func decoderInit(_ model: StructModel) -> [String] {
        var lines = [
            indentUnit + "/// Decodes a `\(model.name)`; forgiving fields degrade to their",
            indentUnit + "/// schema defaults instead of failing the message.",
            indentUnit + "///",
            indentUnit + "/// - Parameter decoder: The decoder positioned at the object.",
            indentUnit + "/// - Throws: `DecodingError` when a strict field is missing, mistyped,",
            indentUnit + "///   or violates a wire invariant.",
            indentUnit + "public init(from decoder: any Decoder) throws {",
            indent2 + "let container = try decoder.container(keyedBy: CodingKeys.self)",
        ]
        for property in model.properties {
            lines.append(indent2 + decodeLine(property))
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders the single decode statement for a property.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `self.x = …` statement.
    private static func decodeLine(_ property: PropertyModel) -> String {
        if property.hasPatchSemantics {
            return patchDecodeLine(property)
        }
        let name = property.swiftName
        let type = property.typeExpression
        switch property.strategy {
        case .strict:
            if let defaultExpression = property.defaultExpression {
                return "self.\(name) = try container.decodeIfPresent(\(type).self, forKey: .\(name)) ?? \(defaultExpression)"
            }
            if property.isOptional {
                return "self.\(name) = try container.decodeIfPresent(\(type).self, forKey: .\(name))"
            }
            return "self.\(name) = try container.decode(\(type).self, forKey: .\(name))"
        case .forgivingScalar:
            if let defaultExpression = property.defaultExpression {
                return "self.\(name) = container.forgivingDecode(\(type).self, forKey: .\(name), default: \(defaultExpression))"
            }
            return "self.\(name) = container.forgivingDecodeIfPresent(\(type).self, forKey: .\(name))"
        case .forgivingArray:
            let element = property.elementType ?? type
            if property.isOptional {
                return "self.\(name) = container.forgivingDecodeArrayIfPresent(of: \(element).self, forKey: .\(name))"
            }
            return "self.\(name) = container.forgivingDecodeArray(of: \(element).self, forKey: .\(name))"
        }
    }

    /// Renders the decode statement for a field with patch semantics, one
    /// `PatchField`-aware helper per decode strategy.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `self.x = …` statement.
    private static func patchDecodeLine(_ property: PropertyModel) -> String {
        let name = property.swiftName
        let type = property.typeExpression
        switch property.strategy {
        case .strict:
            return "self.\(name) = try container.decodePatchField(\(type).self, forKey: .\(name))"
        case .forgivingScalar:
            return "self.\(name) = container.forgivingDecodePatchField(\(type).self, forKey: .\(name))"
        case .forgivingArray:
            let element = property.elementType ?? type
            return "self.\(name) = container.forgivingDecodePatchArray(of: \(element).self, forKey: .\(name))"
        }
    }

    /// Renders `encode(to:)`, omitting `nil` optional fields entirely.
    ///
    /// This mirrors `init(from:)`, which decodes every optional property via
    /// `decodeIfPresent`, so both directions apply the same condition. A
    /// field with patch semantics is the deliberate exception on both sides:
    /// its `.cleared` case decodes from, and encodes as, an explicit `null`.
    ///
    /// - Parameter model: The struct's emission model.
    /// - Returns: The method lines, indented one level.
    private static func encodeMethod(_ model: StructModel) -> [String] {
        var lines = [
            indentUnit + "/// Encodes a `\(model.name)`, omitting nil optional fields — never",
            indentUnit + "/// emitting JSON null for an absent capability-gated field.",
        ]
        if model.properties.contains(where: \.hasPatchSemantics) {
            lines.append(contentsOf: [
                indentUnit + "///",
                indentUnit + "/// A patch-semantics field is the exception: `.cleared` writes an",
                indentUnit + "/// explicit `null` rather than omitting the key, since here `null` is",
                indentUnit + "/// itself the clear signal, not a stand-in for absence.",
            ])
        }
        lines.append(contentsOf: [
            indentUnit + "///",
            indentUnit + "/// - Parameter encoder: The encoder to write the object into.",
            indentUnit + "/// - Throws: Rethrows any error from the underlying encoder.",
            indentUnit + "public func encode(to encoder: any Encoder) throws {",
            indent2 + "var container = encoder.container(keyedBy: CodingKeys.self)",
        ])
        for property in model.properties {
            lines.append(indent2 + encodeCall(property))
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders one keyed `encode` call, omitting nil optionals.
    ///
    /// A field with patch semantics encodes through `encodePatch`, which
    /// chooses between omitting the key, writing `null`, or writing the
    /// value based on the field's case — the inverse of `patchDecodeLine`.
    ///
    /// - Parameter property: The property model.
    /// - Returns: The `try container.encode…` statement, without indentation.
    private static func encodeCall(_ property: PropertyModel) -> String {
        let name = property.swiftName
        if property.hasPatchSemantics {
            return "try container.encodePatch(\(name), forKey: .\(name))"
        }
        if property.isOptional {
            return "try container.encodeIfPresent(\(name), forKey: .\(name))"
        }
        return "try container.encode(\(name), forKey: .\(name))"
    }

    // MARK: - Unions

    /// The doc comment on the synthesized fallback case of a discriminated
    /// enum.
    ///
    /// - Parameter discriminator: The union's discriminator wire name.
    /// - Returns: The `///` lines, indented one level.
    private static func unknownCaseDoc(discriminator: String) -> [String] {
        [
            indentUnit + "/// An unrecognized `\(discriminator)` value, captured alongside the members",
            indentUnit + "/// of the object that no other property owns, so a variant this revision",
            indentUnit + "/// does not list decodes without error and re-encodes unchanged.",
            indentUnit + "///",
            indentUnit + "/// The payload holds neither `\(discriminator)` nor any member declared",
            indentUnit + "/// beside this union: those have their own storage, and a second copy",
            indentUnit + "/// here would win on re-encode. Encoding a payload that declares one is",
            indentUnit + "/// an `EncodingError`.",
        ]
    }

    /// Renders the array literal of member names an unrecognized variant's payload must not hold, because something else encodes them.
    ///
    /// - Parameters:
    ///   - discriminator: The union's discriminator wire name.
    ///   - siblingMembers: Enclosing-object members, empty for a stand-alone
    ///     union.
    /// - Returns: The Swift array literal.
    private static func ownedMembers(discriminator: String, siblingMembers: [String]) -> String {
        "[\(([discriminator] + siblingMembers).map(stringLiteral).joined(separator: ", "))]"
    }

    /// Renders the private constant naming the members an unrecognized variant's payload must not hold.
    ///
    /// The decode arm excludes this list and the encode arm reserves it; both
    /// read the one constant declared here instead of each carrying its own
    /// copy of the literal, so the two cannot drift apart.
    ///
    /// - Parameters:
    ///   - discriminator: The union's discriminator wire name.
    ///   - siblingMembers: Enclosing-object members, empty for a stand-alone
    ///     union.
    /// - Returns: The single declaration line, indented one level.
    private static func excludedMembersDeclaration(discriminator: String, siblingMembers: [String]) -> String {
        indentUnit + "private static let excludedMembers = \(ownedMembers(discriminator: discriminator, siblingMembers: siblingMembers))"
    }

    /// Renders the decode arm that captures an unrecognized discriminator.
    ///
    /// - Parameters:
    ///   - pattern: The `switch` pattern selecting the fallback arm.
    ///   - variable: The name holding the unrecognized discriminator's raw
    ///     string where `pattern` runs — either bound by the pattern itself,
    ///     or captured ahead of the `switch` it belongs to.
    /// - Returns: The arm's two lines, indented two levels.
    private static func unknownDecodeArm(pattern: String, variable: String = "other") -> [String] {
        [
            indent2 + "\(pattern):",
            indent3 + "self = .unknown(\(variable), try JSONValue(from: decoder, excludingMembers: Self.excludedMembers))",
        ]
    }

    /// Renders a private `enum Tag` mapping each entry's Swift case name to
    /// an already-rendered wire-value literal, so that literal is written
    /// once instead of once per read site.
    ///
    /// Shared by every family that repeats a wire constant across a forward
    /// and a reverse lookup: the flattened tagged-union family
    /// (`tagDeclaration`), the discriminated `anyOf` family
    /// (`discriminatedTagDeclaration`), the value-union family
    /// (`valueUnionTagDeclaration`), and scalar enums
    /// (`scalarEnumDeclaration`) — the same single-source-of-truth shape
    /// `excludedMembers` gives the sibling-member list, applied here to a
    /// case's wire value instead.
    ///
    /// - Parameters:
    ///   - entries: Each case's Swift name paired with its literal source
    ///     text (e.g. `"tool_call_update"` or `-32602`), in schema order.
    ///   - rawType: The enum's raw type (`String` for every tag; `String` or
    ///     `Int` for a scalar enum's wire kind).
    ///   - baseIndent: The indentation before `private enum Tag`; case lines
    ///     nest one level deeper.
    /// - Returns: The declaration lines, or empty when there are no entries.
    private static func tagEnumDeclaration(
        entries: [(swiftName: String, literal: String)],
        rawType: String,
        baseIndent: String
    ) -> [String] {
        guard !entries.isEmpty else { return [] }
        var lines = ["\(baseIndent)private enum Tag: \(rawType) {"]
        for entry in entries {
            lines.append("\(baseIndent)\(indentUnit)case \(entry.swiftName) = \(entry.literal)")
        }
        lines.append("\(baseIndent)}")
        return lines
    }

    /// Renders the private `Tag` enum mapping each known tagged-union variant
    /// to the wire discriminator that selects it.
    ///
    /// Decode looks a discriminator up via `Tag(rawValue:)` and encode reads
    /// `Tag.<case>.rawValue` back, so a tag string is written once per case
    /// no matter how many arms use it.
    ///
    /// - Parameter cases: The union's cases in schema order.
    /// - Returns: The declaration lines, indented one level.
    private static func tagDeclaration(cases: [UnionCaseModel]) -> [String] {
        tagEnumDeclaration(
            entries: cases.map { (swiftName: $0.swiftName, literal: stringLiteral($0.tag)) },
            rawType: "String",
            baseIndent: indentUnit
        )
    }

    /// Renders the encode arm that restores an unrecognized variant.
    ///
    /// Reserves the same member names the decode arm excluded, reading the
    /// same `excludedMembers` constant, so a payload built in Swift cannot
    /// overwrite the tag its own case holds or a member of the object the
    /// union is nested in.
    ///
    /// - Parameter discriminator: The union's discriminator wire name.
    /// - Returns: The arm's three lines, indented two levels.
    private static func unknownEncodeArm(discriminator: String) -> [String] {
        [
            indent2 + "case .unknown(let discriminator, let payload):",
            indent3 + "try container.encode(discriminator, forKey: .\(discriminator))",
            indent3 + "try payload.encodeMembers(to: encoder, reserving: Self.excludedMembers)",
        ]
    }

    /// Renders a scalar enum with hand-rolled `Codable`.
    ///
    /// Known wire constants map to named cases, anything else decodes to
    /// `unknown`, and `.unknown` re-encodes the value it captured. Each
    /// case's wire constant is written once, into the nested `Tag` enum;
    /// `wireValue` and `init(wireValue:)` both read it back rather than each
    /// carrying their own copy of the literal.
    ///
    /// - Parameter model: The enum's emission model.
    /// - Returns: The rendered enum declaration.
    static func scalarEnumDeclaration(_ model: ScalarEnumModel) -> String {
        let rawType = model.rawKind.swiftTypeName
        var lines = docLines(model.documentation, indent: "")
        lines.append("public enum \(model.name): Codable, Hashable, Sendable {")
        for enumCase in model.cases {
            lines.append(contentsOf: docLines(enumCase.documentation, indent: indentUnit))
            lines.append(indentUnit + "case \(enumCase.swiftName)")
            lines.append("")
        }
        lines.append(contentsOf: [
            indentUnit + "/// An unrecognized wire value, captured verbatim so a newer peer's",
            indentUnit + "/// value decodes without error and re-encodes unchanged.",
            indentUnit + "case unknown(\(rawType))",
            "",
        ])
        lines.append(contentsOf: tagEnumDeclaration(
            entries: model.cases.map { (swiftName: $0.swiftName, literal: wireLiteral($0, kind: model.rawKind)) },
            rawType: rawType,
            baseIndent: indentUnit
        ))
        lines.append(contentsOf: [
            "",
            indentUnit + "/// The value as it crosses the wire.",
            indentUnit + "public var wireValue: \(rawType) {",
            indent2 + "switch self {",
        ])
        for enumCase in model.cases {
            lines.append(indent2 + "case .\(enumCase.swiftName): Tag.\(enumCase.swiftName).rawValue")
        }
        lines.append(contentsOf: [
            indent2 + "case .unknown(let value): value",
            indent2 + "}",
            indentUnit + "}",
            "",
            indentUnit + "/// Creates the case matching a wire value, routing unrecognized",
            indentUnit + "/// values to `.unknown`.",
            indentUnit + "///",
            indentUnit + "/// - Parameter wireValue: The value as it crosses the wire.",
            indentUnit + "public init(wireValue: \(rawType)) {",
            indent2 + "switch wireValue {",
        ])
        for enumCase in model.cases {
            lines.append(indent2 + "case Tag.\(enumCase.swiftName).rawValue: self = .\(enumCase.swiftName)")
        }
        lines.append(contentsOf: [
            indent2 + "default: self = .unknown(wireValue)",
            indent2 + "}",
            indentUnit + "}",
            "",
            indentUnit + "/// Decodes the wire value, never failing on unrecognized values.",
            indentUnit + "///",
            indentUnit + "/// - Parameter decoder: The decoder positioned at the value.",
            indentUnit + "/// - Throws: `DecodingError` when the wire value is not a \(rawType).",
            indentUnit + "public init(from decoder: any Decoder) throws {",
            indent2 + "self.init(wireValue: try decoder.singleValueContainer().decode(\(rawType).self))",
            indentUnit + "}",
            "",
            indentUnit + "/// Encodes the wire value; `.unknown` re-emits the value it captured.",
            indentUnit + "///",
            indentUnit + "/// - Parameter encoder: The encoder to write the value into.",
            indentUnit + "/// - Throws: Rethrows any error from the underlying encoder.",
            indentUnit + "public func encode(to encoder: any Encoder) throws {",
            indent2 + "var container = encoder.singleValueContainer()",
            indent2 + "try container.encode(wireValue)",
            indentUnit + "}",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    /// Renders one scalar-enum case's wire constant as a Swift literal.
    ///
    /// String constants are escaped here rather than at the generator
    /// boundary, so no schema value can break out of the emitted source even
    /// if it reaches the emitter unvalidated.
    ///
    /// - Parameters:
    ///   - enumCase: The case model.
    ///   - kind: The enum's raw kind.
    /// - Returns: The literal's source text.
    private static func wireLiteral(_ enumCase: EnumCaseModel, kind: EnumRawKind) -> String {
        switch kind {
        case .string: stringLiteral(enumCase.wireValue)
        case .integer: enumCase.wireValue
        }
    }

    /// Renders the private `CodingKeys` enum that names a union's coding
    /// keys. Shared by `taggedUnionDeclaration` and
    /// `discriminatedUnionDeclaration`, which each pass a single-element
    /// array naming their discriminator field, and by `valueUnionEnum`, which
    /// passes both its discriminator and value wire-name fields.
    ///
    /// - Parameters:
    ///   - cases: The coding keys' Swift names, in declaration order.
    ///   - baseIndent: The indentation the enum declaration itself sits at.
    /// - Returns: The declaration lines: an opening brace, one `case` line
    ///   per entry in `cases`, and a closing brace.
    private static func unionCodingKeysDeclaration(cases: [String], baseIndent: String) -> [String] {
        [baseIndent + "private enum CodingKeys: String, CodingKey {"]
            + cases.map { baseIndent + indentUnit + "case \($0)" }
            + [baseIndent + "}"]
    }

    /// Renders a tagged union as an enum with hand-rolled `Codable`.
    ///
    /// Cases carry associated payload values and coding is keyed on the
    /// discriminator: the payload's fields sit flattened beside the
    /// discriminator (serde's internally-tagged representation), and
    /// unrecognized discriminators decode to `unknown(String)`.
    ///
    /// - Parameter model: The union's emission model.
    /// - Returns: The rendered enum declaration.
    static func taggedUnionDeclaration(_ model: TaggedUnionModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public enum \(model.name): Codable, Hashable, Sendable {")
        for unionCase in model.cases {
            lines.append(contentsOf: docLines(unionCase.documentation, indent: indentUnit))
            if let payload = unionCase.payloadType {
                lines.append(indentUnit + "case \(unionCase.swiftName)(\(payload))")
            } else {
                lines.append(indentUnit + "case \(unionCase.swiftName)")
            }
            lines.append("")
        }
        lines.append(contentsOf: unknownCaseDoc(discriminator: model.discriminator))
        lines.append(indentUnit + "case unknown(String, JSONValue)")
        lines.append("")
        lines.append(contentsOf: unionCodingKeysDeclaration(cases: [model.discriminator], baseIndent: indentUnit))
        lines.append("")
        lines.append(contentsOf: tagDeclaration(cases: model.cases))
        lines.append("")
        lines.append(excludedMembersDeclaration(discriminator: model.discriminator, siblingMembers: model.siblingMembers))
        lines.append(contentsOf: [
            "",
            indentUnit + "/// Decodes by the `\(model.discriminator)` discriminator, routing",
            indentUnit + "/// unrecognized values to `.unknown`.",
            indentUnit + "///",
            indentUnit + "/// - Parameter decoder: The decoder positioned at the object.",
            indentUnit + "/// - Throws: `DecodingError` when the discriminator is missing or a",
            indentUnit + "///   known variant's payload is malformed.",
            indentUnit + "public init(from decoder: any Decoder) throws {",
            indent2 + "let container = try decoder.container(keyedBy: CodingKeys.self)",
            indent2 + "let discriminator = try container.decode(String.self, forKey: .\(model.discriminator))",
            indent2 + "switch Tag(rawValue: discriminator) {",
        ])
        for unionCase in model.cases {
            lines.append(indent2 + "case .\(unionCase.swiftName):")
            if let payload = unionCase.payloadType {
                lines.append(indent3 + "self = .\(unionCase.swiftName)(try \(payload)(from: decoder))")
            } else {
                lines.append(indent3 + "self = .\(unionCase.swiftName)")
            }
        }
        lines.append(contentsOf: unknownDecodeArm(pattern: "case nil", variable: "discriminator"))
        lines.append(contentsOf: [
            indent2 + "}",
            indentUnit + "}",
            "",
            indentUnit + "/// Encodes the `\(model.discriminator)` discriminator, flattening the",
            indentUnit + "/// payload's fields into the same object.",
            indentUnit + "///",
            indentUnit + "/// - Parameter encoder: The encoder to write the object into.",
            indentUnit + "/// - Throws: Rethrows any error from the underlying encoder.",
            indentUnit + "public func encode(to encoder: any Encoder) throws {",
            indent2 + "var container = encoder.container(keyedBy: CodingKeys.self)",
            indent2 + "switch self {",
        ])
        for unionCase in model.cases {
            if unionCase.payloadType != nil {
                lines.append(indent2 + "case .\(unionCase.swiftName)(let payload):")
                lines.append(indent3 + "try container.encode(Tag.\(unionCase.swiftName).rawValue, forKey: .\(model.discriminator))")
                lines.append(indent3 + "try payload.encode(to: encoder)")
            } else {
                lines.append(indent2 + "case .\(unionCase.swiftName):")
                lines.append(indent3 + "try container.encode(Tag.\(unionCase.swiftName).rawValue, forKey: .\(model.discriminator))")
            }
        }
        lines.append(contentsOf: unknownEncodeArm(discriminator: model.discriminator))
        lines.append(contentsOf: [
            indent2 + "}",
            indentUnit + "}",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    /// Renders the private `Tag` enum mapping each discriminated-union
    /// variant with a `const` tag to the wire discriminator that selects it.
    ///
    /// The default variant (`nil` tag) has no entry, since no discriminator
    /// string selects it — it is what an *absent* discriminator selects.
    ///
    /// - Parameter cases: The union's cases in schema order.
    /// - Returns: The declaration lines, indented one level.
    private static func discriminatedTagDeclaration(cases: [DiscriminatedCaseModel]) -> [String] {
        let tagged = cases.compactMap { unionCase -> (swiftName: String, literal: String)? in
            unionCase.tag.map { (unionCase.swiftName, stringLiteral($0)) }
        }
        return tagEnumDeclaration(entries: tagged, rawType: "String", baseIndent: indentUnit)
    }

    /// Renders a discriminated `anyOf` union as an enum with hand-rolled
    /// `Codable`.
    ///
    /// Each case wraps a payload struct flattened beside the discriminator. An
    /// absent discriminator selects the default variant; an unrecognized one
    /// decodes to `unknown(String)`, which re-encodes just the discriminator.
    ///
    /// - Parameter model: The discriminated-union emission model.
    /// - Returns: The rendered enum declaration.
    static func discriminatedUnionDeclaration(_ model: DiscriminatedUnionModel) -> String {
        var lines = docLines(model.documentation, indent: "")
        lines.append("public enum \(model.name): Codable, Hashable, Sendable {")
        for unionCase in model.cases {
            lines.append(contentsOf: docLines(unionCase.documentation, indent: indentUnit))
            lines.append(indentUnit + "case \(unionCase.swiftName)(\(unionCase.payloadType))")
            lines.append("")
        }
        lines.append(contentsOf: unknownCaseDoc(discriminator: model.discriminator))
        lines.append(indentUnit + "case unknown(String, JSONValue)")
        lines.append("")
        lines.append(contentsOf: unionCodingKeysDeclaration(cases: [model.discriminator], baseIndent: indentUnit))
        lines.append("")
        lines.append(contentsOf: discriminatedTagDeclaration(cases: model.cases))
        lines.append("")
        lines.append(excludedMembersDeclaration(discriminator: model.discriminator, siblingMembers: []))
        lines.append(contentsOf: [
            "",
            indentUnit + "/// Decodes by the `\(model.discriminator)` discriminator; an absent",
            indentUnit + "/// discriminator selects the default variant and an unrecognized one",
            indentUnit + "/// routes to `.unknown`.",
            indentUnit + "///",
            indentUnit + "/// - Parameter decoder: The decoder positioned at the object.",
            indentUnit + "/// - Throws: `DecodingError` when a known variant's payload is malformed.",
            indentUnit + "public init(from decoder: any Decoder) throws {",
            indent2 + "let container = try decoder.container(keyedBy: CodingKeys.self)",
            indent2 + "switch try container.decodeIfPresent(String.self, forKey: .\(model.discriminator)) {",
        ])
        for unionCase in model.cases {
            guard unionCase.tag != nil else { continue }
            lines.append(indent2 + "case Tag.\(unionCase.swiftName).rawValue?:")
            lines.append(indent3 + "self = .\(unionCase.swiftName)(try \(unionCase.payloadType)(from: decoder))")
        }
        if let defaultCase = model.cases.first(where: { $0.tag == nil }) {
            lines.append(indent2 + "case nil:")
            lines.append(indent3 + "self = .\(defaultCase.swiftName)(try \(defaultCase.payloadType)(from: decoder))")
        }
        lines.append(contentsOf: unknownDecodeArm(pattern: "case let other?"))
        lines.append(contentsOf: [
            indent2 + "}",
            indentUnit + "}",
            "",
            indentUnit + "/// Encodes the `\(model.discriminator)` discriminator, flattening the",
            indentUnit + "/// payload's fields into the same object; the default variant omits",
            indentUnit + "/// the discriminator.",
            indentUnit + "///",
            indentUnit + "/// - Parameter encoder: The encoder to write the object into.",
            indentUnit + "/// - Throws: Rethrows any error from the underlying encoder.",
            indentUnit + "public func encode(to encoder: any Encoder) throws {",
            indent2 + "var container = encoder.container(keyedBy: CodingKeys.self)",
            indent2 + "switch self {",
        ])
        for unionCase in model.cases {
            lines.append(indent2 + "case .\(unionCase.swiftName)(let payload):")
            if unionCase.tag != nil {
                lines.append(indent3 + "try container.encode(Tag.\(unionCase.swiftName).rawValue, forKey: .\(model.discriminator))")
            }
            lines.append(indent3 + "try payload.encode(to: encoder)")
        }
        lines.append(contentsOf: unknownEncodeArm(discriminator: model.discriminator))
        lines.append(contentsOf: [
            indent2 + "}",
            indentUnit + "}",
            "}",
        ])
        return lines.joined(separator: "\n")
    }

    // MARK: - Objects carrying a union

    /// The reserved wire member ACP attaches metadata to, always emitted last.
    private static let metaWireName = "_meta"

    /// The union portion of an object that carries one, as the struct emitter
    /// needs it.
    ///
    /// The two families differ only in what the nested enum looks like and
    /// what the stored property is called; the surrounding struct — members,
    /// initializer, coding keys, and both Codable halves — is identical, since
    /// in both cases the union's own Codable flattens into the same object.
    private struct FlattenedUnion {
        /// The wire member name the union occupies (`value`, `operation`).
        let wireName: String

        /// The nested enum's Swift type name.
        let typeName: String

        /// The doc comment on the struct's stored property, without `///`.
        let documentation: String

        /// The rendered nested enum, indented one level.
        let declaration: [String]
    }

    /// Renders an object definition that carries a value union.
    ///
    /// - Parameter model: The object-value-union emission model.
    /// - Returns: The rendered struct declaration.
    static func objectValueUnionDeclaration(_ model: ObjectValueUnionModel) -> String {
        objectCarryingAUnion(
            base: model.base,
            union: FlattenedUnion(
                wireName: model.valueWireName,
                typeName: model.valueEnumName,
                documentation: "The value carried beside the object's own members, selected by its `\(model.discriminator)` discriminator.",
                declaration: valueUnionEnum(model)
            )
        )
    }

    /// Renders an object definition that carries a tagged `$ref`-payload union.
    ///
    /// - Parameter model: The object-tagged-union emission model.
    /// - Returns: The rendered struct declaration.
    static func objectTaggedUnionDeclaration(_ model: ObjectTaggedUnionModel) -> String {
        objectCarryingAUnion(
            base: model.base,
            union: FlattenedUnion(
                wireName: model.union.discriminator,
                typeName: model.union.name,
                documentation: "The variant payload, whose own members sit flattened beside this object's.",
                declaration: indented(declaration: taggedUnionDeclaration(model.union))
                    .split(separator: "\n", omittingEmptySubsequences: false)
                    .map(String.init)
            )
        )
    }

    /// Renders the struct wrapping an object's flattened union.
    ///
    /// The base object properties become ordinary struct members; the union
    /// becomes a nested enum whose payload flattens beside them. Decoding and
    /// encoding delegate the union portion to that enum.
    ///
    /// - Parameters:
    ///   - base: The base struct model.
    ///   - union: The union portion.
    /// - Returns: The rendered struct declaration.
    private static func objectCarryingAUnion(base: StructModel, union: FlattenedUnion) -> String {
        let meta = base.properties.first { $0.wireName == metaWireName }
        let leading = base.properties.filter { $0.wireName != metaWireName }

        var lines = docLines(base.documentation, indent: "")
        lines.append("public struct \(base.name): Codable, Hashable, Sendable {")
        lines.append(contentsOf: union.declaration)
        for property in leading {
            lines.append("")
            lines.append(contentsOf: docLines(property.documentation, indent: indentUnit))
            lines.append(indentUnit + "public var \(property.swiftName): \(renderedType(of: property))")
        }
        lines.append("")
        lines.append(contentsOf: docLines(union.documentation, indent: indentUnit))
        lines.append(indentUnit + "public var \(union.wireName): \(union.typeName)")
        if let meta {
            lines.append("")
            lines.append(contentsOf: docLines(meta.documentation, indent: indentUnit))
            lines.append(indentUnit + "public var \(meta.swiftName): \(renderedType(of: meta))")
        }
        lines.append("")
        lines.append(contentsOf: unionStructInit(base: base, union: union, leading: leading, meta: meta))
        lines.append("")
        lines.append(contentsOf: codingKeys(base))
        lines.append("")
        lines.append(contentsOf: unionStructDecoder(base: base, union: union, leading: leading, meta: meta))
        lines.append("")
        lines.append(contentsOf: unionStructEncoder(base: base, union: union, leading: leading, meta: meta))
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    /// Renders the nested value-union enum with hand-rolled `Codable`.
    ///
    /// - Parameter model: The object-value-union emission model.
    /// - Returns: The enum lines, indented one level.
    private static func valueUnionEnum(_ model: ObjectValueUnionModel) -> [String] {
        var lines = [
            indentUnit + "/// The value payload, selected by the `\(model.discriminator)` discriminator.",
            indentUnit + "public enum \(model.valueEnumName): Codable, Hashable, Sendable {",
        ]
        for unionCase in model.cases {
            lines.append(contentsOf: docLines(unionCase.documentation, indent: indent2))
            lines.append(indent2 + "case \(unionCase.swiftName)(\(caseAssociatedValues(of: unionCase)))")
        }
        lines.append("")
        lines.append(contentsOf: unionCodingKeysDeclaration(cases: [model.discriminator, model.valueWireName], baseIndent: indent2))
        lines.append("")
        let tagDeclaration = valueUnionTagDeclaration(cases: model.cases)
        if !tagDeclaration.isEmpty {
            lines.append(contentsOf: tagDeclaration)
            lines.append("")
        }
        lines.append(contentsOf: valueUnionDecoder(model))
        lines.append("")
        lines.append(contentsOf: valueUnionEncoder(model))
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders the private enum mapping each `const`-pinned value-union
    /// variant to its wire discriminator, or no lines when no variant pins
    /// one (an all-default union has no tag to deduplicate).
    ///
    /// Decode looks a discriminator up via `Tag(rawValue:)` and encode reads
    /// `Tag.<case>.rawValue` back — the same single-source-of-truth shape
    /// `tagDeclaration` gives the flattened tagged-union family.
    ///
    /// - Parameter cases: The value union's cases in schema order.
    /// - Returns: The declaration lines, indented two levels, or empty.
    private static func valueUnionTagDeclaration(cases: [ValueUnionCaseModel]) -> [String] {
        let tagged = cases.compactMap { unionCase -> (swiftName: String, literal: String)? in
            guard case .tag(let tag) = unionCase.selector else { return nil }
            return (unionCase.swiftName, stringLiteral(tag))
        }
        return tagEnumDeclaration(entries: tagged, rawType: "String", baseIndent: indent2)
    }

    /// Renders one value-union case's associated-value list.
    ///
    /// The catch-all default takes the matched discriminator ahead of the
    /// value, since it is the one case whose tag is not fixed by its name.
    ///
    /// - Parameter unionCase: The value-union case model.
    /// - Returns: The associated-value types, comma-separated.
    private static func caseAssociatedValues(of unionCase: ValueUnionCaseModel) -> String {
        switch unionCase.selector {
        case .tag, .untagged:
            unionCase.valueType
        case .capturedTag:
            "String, \(unionCase.valueType)"
        }
    }

    /// Renders `init(from:)` for a nested value-union enum.
    ///
    /// A catch-all default binds the discriminator it matched, so the
    /// discriminator decodes strictly; a default that declares no discriminator
    /// is instead what an *absent* one selects, so there it decodes leniently.
    ///
    /// - Parameter model: The object-value-union emission model.
    /// - Returns: The initializer lines, indented two levels.
    private static func valueUnionDecoder(_ model: ObjectValueUnionModel) -> [String] {
        let capturesTag = model.cases.contains { $0.selector == .capturedTag }
        var lines = [indent2 + "/// Decodes the value by its `\(model.discriminator)` discriminator,"]
        if capturesTag {
            lines.append(contentsOf: [
                indent2 + "/// routing an unrecognized value to the default variant, which",
                indent2 + "/// captures it so it round-trips unchanged on re-encode.",
            ])
        } else {
            lines.append(contentsOf: [
                indent2 + "/// falling back to the default variant when it is absent. That",
                indent2 + "/// variant's own schema places no constraint on this member, so a",
                indent2 + "/// present-but-unrecognized value also matches it — and, having no",
                indent2 + "/// discriminator member of its own, does not round-trip on re-encode.",
            ])
        }
        lines.append(contentsOf: [
            indent2 + "///",
            indent2 + "/// - Parameter decoder: The decoder positioned at the object.",
            indent2 + "/// - Throws: `DecodingError` when the payload is missing or mistyped.",
            indent2 + "public init(from decoder: any Decoder) throws {",
            indent3 + "let container = try decoder.container(keyedBy: CodingKeys.self)",
        ])
        let hasTaggedCases = model.cases.contains {
            if case .tag = $0.selector { return true }
            return false
        }
        lines.append(contentsOf: hasTaggedCases
            ? valueUnionDecoderBody(model, capturesTag: capturesTag)
            : valueUnionDecoderBodyWithoutTaggedCases(model, capturesTag: capturesTag))
        return lines
    }

    /// Renders the `switch`, one arm per `.tag` case, that decodes a value
    /// union with at least one `const`-pinned variant.
    ///
    /// Reads the discriminator into a local once, so both the `Tag` lookup
    /// and the fallback arm that needs the raw string share one decode.
    ///
    /// - Parameters:
    ///   - model: The object-value-union emission model.
    ///   - capturesTag: Whether the default variant captures the tag it
    ///     matched, deciding whether the discriminator decodes strictly.
    /// - Returns: The `switch` and its closing braces, indented three levels.
    private static func valueUnionDecoderBody(_ model: ObjectValueUnionModel, capturesTag: Bool) -> [String] {
        var lines: [String] = []
        if capturesTag {
            lines.append(indent3 + "let discriminator = try container.decode(String.self, forKey: .\(model.discriminator))")
            lines.append(indent3 + "switch Tag(rawValue: discriminator) {")
        } else {
            lines.append(indent3 + "let discriminator = try container.decodeIfPresent(String.self, forKey: .\(model.discriminator))")
            lines.append(indent3 + "switch discriminator.flatMap(Tag.init(rawValue:)) {")
        }
        for unionCase in model.cases {
            guard case .tag = unionCase.selector else { continue }
            lines.append(indent3 + "case .\(unionCase.swiftName):")
            lines.append(indent4 + "self = .\(unionCase.swiftName)(\(valueDecodeCall(unionCase, model)))")
        }
        for unionCase in model.cases {
            switch unionCase.selector {
            case .tag:
                continue
            case .untagged:
                lines.append(indent3 + "case nil:")
                lines.append(indent4 + "self = .\(unionCase.swiftName)(\(valueDecodeCall(unionCase, model)))")
            case .capturedTag:
                lines.append(indent3 + "case nil:")
                lines.append(indent4 + "self = .\(unionCase.swiftName)(discriminator, \(valueDecodeCall(unionCase, model)))")
            }
        }
        lines.append(contentsOf: [indent3 + "}", indent2 + "}"])
        return lines
    }

    /// Renders the `switch` that decodes a value union with no `.tag` case —
    /// a lone discriminator-less default, with no `Tag` table to read from.
    ///
    /// - Parameters:
    ///   - model: The object-value-union emission model.
    ///   - capturesTag: Whether the default variant captures the tag it
    ///     matched, deciding whether the discriminator decodes strictly.
    /// - Returns: The `switch` and its closing braces, indented three levels.
    private static func valueUnionDecoderBodyWithoutTaggedCases(
        _ model: ObjectValueUnionModel,
        capturesTag: Bool
    ) -> [String] {
        let subject = capturesTag
            ? "try container.decode(String.self, forKey: .\(model.discriminator))"
            : "try container.decodeIfPresent(String.self, forKey: .\(model.discriminator))"
        var lines = [indent3 + "switch \(subject) {"]
        for unionCase in model.cases {
            switch unionCase.selector {
            case .tag:
                continue
            case .untagged:
                lines.append(indent3 + "default:")
                lines.append(indent4 + "self = .\(unionCase.swiftName)(\(valueDecodeCall(unionCase, model)))")
            case .capturedTag:
                lines.append(indent3 + "case let other:")
                lines.append(indent4 + "self = .\(unionCase.swiftName)(other, \(valueDecodeCall(unionCase, model)))")
            }
        }
        lines.append(contentsOf: [indent3 + "}", indent2 + "}"])
        return lines
    }

    /// Renders the keyed decode call for a value-union case's payload.
    ///
    /// - Parameters:
    ///   - unionCase: The value-union case model.
    ///   - model: The object-value-union emission model.
    /// - Returns: The `try container.decode…` expression.
    private static func valueDecodeCall(_ unionCase: ValueUnionCaseModel, _ model: ObjectValueUnionModel) -> String {
        "try container.decode(\(unionCase.valueType).self, forKey: .\(model.valueWireName))"
    }

    /// Renders `encode(to:)` for a nested value-union enum.
    ///
    /// - Parameter model: The object-value-union emission model.
    /// - Returns: The method lines, indented two levels.
    private static func valueUnionEncoder(_ model: ObjectValueUnionModel) -> [String] {
        var lines = [
            indent2 + "/// Encodes the value, flattening its payload beside the object's own",
            indent2 + "/// members; a default variant declaring no discriminator omits it.",
            indent2 + "///",
            indent2 + "/// - Parameter encoder: The encoder to write the object into.",
            indent2 + "/// - Throws: Rethrows any error from the underlying encoder.",
            indent2 + "public func encode(to encoder: any Encoder) throws {",
            indent3 + "var container = encoder.container(keyedBy: CodingKeys.self)",
            indent3 + "switch self {",
        ]
        for unionCase in model.cases {
            switch unionCase.selector {
            case .tag:
                lines.append(indent3 + "case .\(unionCase.swiftName)(let payload):")
                lines.append(indent4 + "try container.encode(Tag.\(unionCase.swiftName).rawValue, forKey: .\(model.discriminator))")
            case .untagged:
                lines.append(indent3 + "case .\(unionCase.swiftName)(let payload):")
            case .capturedTag:
                lines.append(indent3 + "case .\(unionCase.swiftName)(let discriminator, let payload):")
                lines.append(indent4 + "try container.encode(discriminator, forKey: .\(model.discriminator))")
            }
            lines.append(indent4 + "try container.encode(payload, forKey: .\(model.valueWireName))")
        }
        lines.append(contentsOf: [indent3 + "}", indent2 + "}"])
        return lines
    }

    /// Renders the memberwise initializer for an object carrying a union.
    ///
    /// - Parameters:
    ///   - base: The base struct model.
    ///   - union: The union portion.
    ///   - leading: The base properties preceding the union member.
    ///   - meta: The `_meta` property, if present.
    /// - Returns: The initializer lines, indented one level.
    private static func unionStructInit(
        base: StructModel,
        union: FlattenedUnion,
        leading: [PropertyModel],
        meta: PropertyModel?
    ) -> [String] {
        var parameters = leading.map(initParameter)
        parameters.append("\(union.wireName): \(union.typeName)")
        if let meta {
            parameters.append(initParameter(meta))
        }
        var lines = [indentUnit + "/// Creates a `\(base.name)`.", indentUnit + "public init("]
        lines.append(contentsOf: renderParameters(items: parameters, render: { $0 }))
        lines.append(indentUnit + ") {")
        for property in leading {
            lines.append(indent2 + "self.\(property.swiftName) = \(property.swiftName)")
        }
        lines.append(indent2 + "self.\(union.wireName) = \(union.wireName)")
        if let meta {
            lines.append(indent2 + "self.\(meta.swiftName) = \(meta.swiftName)")
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders `init(from:)` for an object carrying a union.
    ///
    /// - Parameters:
    ///   - base: The base struct model.
    ///   - union: The union portion.
    ///   - leading: The base properties preceding the union member.
    ///   - meta: The `_meta` property, if present.
    /// - Returns: The initializer lines, indented one level.
    private static func unionStructDecoder(
        base: StructModel,
        union: FlattenedUnion,
        leading: [PropertyModel],
        meta: PropertyModel?
    ) -> [String] {
        var lines = [
            indentUnit + "/// Decodes a `\(base.name)`; forgiving fields degrade to their",
            indentUnit + "/// schema defaults instead of failing the message.",
            indentUnit + "///",
            indentUnit + "/// - Parameter decoder: The decoder positioned at the object.",
            indentUnit + "/// - Throws: `DecodingError` when a strict field is missing or mistyped.",
            indentUnit + "public init(from decoder: any Decoder) throws {",
            indent2 + "let container = try decoder.container(keyedBy: CodingKeys.self)",
        ]
        for property in leading {
            lines.append(indent2 + decodeLine(property))
        }
        lines.append(indent2 + "self.\(union.wireName) = try \(union.typeName)(from: decoder)")
        if let meta {
            lines.append(indent2 + decodeLine(meta))
        }
        lines.append(indentUnit + "}")
        return lines
    }

    /// Renders `encode(to:)` for an object carrying a union.
    ///
    /// - Parameters:
    ///   - base: The base struct model.
    ///   - union: The union portion.
    ///   - leading: The base properties preceding the union member.
    ///   - meta: The `_meta` property, if present.
    /// - Returns: The method lines, indented one level.
    private static func unionStructEncoder(
        base: StructModel,
        union: FlattenedUnion,
        leading: [PropertyModel],
        meta: PropertyModel?
    ) -> [String] {
        var lines = [
            indentUnit + "/// Encodes a `\(base.name)`, omitting nil optional fields.",
            indentUnit + "///",
            indentUnit + "/// - Parameter encoder: The encoder to write the object into.",
            indentUnit + "/// - Throws: Rethrows any error from the underlying encoder.",
            indentUnit + "public func encode(to encoder: any Encoder) throws {",
            indent2 + "var container = encoder.container(keyedBy: CodingKeys.self)",
        ]
        for property in leading {
            lines.append(indent2 + encodeCall(property))
        }
        lines.append(indent2 + "try \(union.wireName).encode(to: encoder)")
        if let meta {
            lines.append(indent2 + encodeCall(meta))
        }
        lines.append(indentUnit + "}")
        return lines
    }

    // MARK: - Documentation

    /// Renders a schema description as doc-comment lines.
    ///
    /// - Parameters:
    ///   - text: The schema `description`, if any.
    ///   - indent: The indentation prefix for each line.
    /// - Returns: `///` lines, or empty when there is no description.
    private static func docLines(_ text: String?, indent: String) -> [String] {
        guard let text, !text.isEmpty else { return [] }
        return text.split(separator: "\n", omittingEmptySubsequences: false).map { line in
            line.isEmpty ? "\(indent)///" : "\(indent)/// \(line)"
        }
    }
}
